<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ab.ms</groupId>
    <artifactId>services</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>services</name>
    <description>Aggregator for microservice modules</description>

    <modules>
        <module>accounts</module>
        <module>cards</module>
        <module>configserver</module>
        <module>customer</module>
        <module>eurekaserver</module>
        <module>gatewayserver</module>
        <module>loans</module>
        <module>message</module>
        <module>order</module>
        <module>inventory</module>
        <module>payment</module>
    </modules>
</project>
