CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(64) NOT NULL,
    available_quantity INT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT uq_inventory_items_product_id UNIQUE (product_id),
    CONSTRAINT chk_inventory_items_qty CHECK (available_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_reservation_product FOREIGN KEY (product_id) REFERENCES inventory_items (product_id),
    CONSTRAINT chk_inventory_reservations_qty CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_inventory_reservations_order_id ON inventory_reservations (order_id);

INSERT INTO inventory_items (product_id, available_quantity, version, created_at, updated_at)
VALUES ('K100', 500, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('K200', 500, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('K300', 500, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('K400', 500, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('K500', 500, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
