build:
  version: "3.0"

customer:
  message: "Welcome to ABMS customer local APIs"
  contactDetails:
    name: "Aidan Adrian"
    email: "aidanadrian@email.com"
  onCallSupport:
    - (270) 320 8732
    - (270) 452 1358