build:
  version: "2.0"

order:
  message: "Welcome to ABMS order QA APIs"
  contactDetails:
    name: "Kaiser Jaeri - QA Lead"
    email: "kaiserjaeri@email.com"
  onCallSupport:
    - (440) 429 8321
    - (440) 438 4720